<?php
/**
 * HelpDesk Block - Adminhtml CaseItem View System Reply Renderer Template
 *
 * view/adminhtml/templates/case/view/tab/replies/user.phtml
 *
 * =============================================================================
 *
 * @package    Dem\HelpDesk
 * @copyright  Copyright (c) 2021 Direct Edge Media (http://directedgemedia.com)
 * @author     Toby Crain
 * @since      1.0.0
 *
 * Valid template variable codes
 * @see \Dem\HelpDesk\Block\Adminhtml\CaseItem\View\Tabs::renderReplyBlock()
 *
 * {{reply-class}}
 * {{reply-date}}
 * {{reply-author}}
 * {{reply-text}}
 * {{status-label}}
 * {{reply-status}}
 */
?>
<table class="admin__table-secondary reply {{reply-class}}">
    <thead>
        <th class="reply-date">{{reply-date}}</th>
        <th class="reply-author">{{reply-author}}</th>
    </thead>
    <tbody>
        <tr>
            <td colspan="2" class="reply-text">{{reply-text}}</td>
        </tr>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="2" class="reply-status">
                {{status-label}}: {{reply-status}}
            </td>
        </tr>
    </tfoot>
</table>