<?php
/**
 * HelpDesk Block - Adminhtml CaseItem View Tab Info
 *
 * =============================================================================
 *
 * @package    Dem\HelpDesk
 * @copyright  Copyright (c) 2021 Direct Edge Media (http://directedgemedia.com)
 * @author     Toby Crain
 * @since      1.0.0
 */

/* @var $block \Dem\HelpDesk\Block\Adminhtml\CaseItem\View\Tab\Info */
/* @var $replyItems \Dem\HelpDesk\Api\Data\ReplyInterface [] */
$replyItems = $block->getVisibleReplies(3);
$case = $block->getCase();
?>

<div class="fieldset-wrapper case-information">
    <div class="fieldset-wrapper-title">
        <span class="title"><?= $block->escapeHtml(__('Subject')) ?>:
            <span class="case-subject"><?= $block->escapeHtml($block->getSubject()) ?></span>
        </span>
    </div>
    <table class="admin__table-secondary half-width">
        <tbody>
            <tr>
                <th><?= $block->escapeHtml(__('Case')) ?> #:</th>
                <td>
                    <span class="case-number">
                        <?= $block->escapeHtml($block->getCaseNumber()); ?>
                    </span>
                </td>
            </tr>
            <tr>
                <th><?= $block->escapeHtml(__('Created At')) ?>:</th>
                <td>
                    <span class="created-at">
                        <?= $block->escapeHtml($block->getCreatedDate($case)) ?>
                    </span>
                </td>
            </tr>
            <tr>
                <th><?= $block->escapeHtml(__('Created By')) ?>:</th>
                <td>
                    <span class="creator-name">
                    <?php if ($block->isCustomerCreator()): ?>
                        <?= sprintf(
                            '<a href="%s">%s</a>',
                            $block->getCustomerCreatorUrl(),
                            $block->escapeHtml($block->getCreatorName())
                        ) ?>
                    <?php else: ?>
                        <?= $block->escapeHtml($block->getCreatorName()) ?>
                    <?php endif ?>
                    </span>
                </td>
            </tr>
            <tr>
                <th><?= $block->escapeHtml(__('Created from IP')) ?>:</th>
                <td>
                    <span class="remote-ip">
                        <?= ($block->getRemoteIp()) ? $block->escapeHtml($block->getRemoteIp()) : __('n/a'); ?>
                    </span>
                </td>
            </tr>
            <tr>
                <th><?= $block->escapeHtml(__('Website')) ?>:</th>
                <td>
                    <span class="website-name">
                        <?= $block->escapeHtml($block->getWebsiteName()); ?>
                    </span>
                </td>
            </tr>
            <tr>
                <th><?= $block->escapeHtml(__('Department')) ?>:</th>
                <td>
                    <span class="department-name">
                        <?= $block->escapeHtml($block->getDepartmentName()); ?>
                    </span>
                </td>
            </tr>
        </tbody>
    </table>

    <table class="admin__table-secondary half-width">
        <tbody>
            <tr>
                <th><?= $block->escapeHtml(__('Case Manager')) ?>:</th>
                <td>
                    <span class="case-manager-name">
                        <?= $block->escapeHtml($block->getCaseManagerName()); ?>
                    </span>
                </td>
            </tr>
            <tr>
                <th><?= $block->escapeHtml(__('Case Status')) ?>:</th>
                <td>
                    <span class="<?= $block->getStatusItem($case)->getCssClass() ?>">
                        <?= $block->escapeHtml($block->getStatusItem($case)->getLabel()) ?>
                    </span>
                </td>
            </tr>
            <tr>
                <th><?= $block->escapeHtml(__('Priority')) ?>:</th>
                <td>
                    <span class="<?= $block->getPriorityItem()->getCssClass() ?>">
                        <?= $block->escapeHtml($block->getPriorityItem()->getLabel()) ?>
                    </span>
                </td>
            </tr>
            <tr>
                <th><?= $block->escapeHtml(__('Updated At')) ?>:</th>
                <td>
                    <span class="updated-at">
                        <?= ($block->getUpdatedDate($case)) ? $block->escapeHtml($block->getUpdatedDate($case)) : __('n/a'); ?>
                    </span>
                </td>
            </tr>
            <tr>
                <th><?= $block->escapeHtml(__('Updated By')) ?>:</th>
                <td>
                    <span class="updater-name">
                        <?= ($block->getUpdaterName()) ? $block->escapeHtml($block->getUpdaterName()) : __('n/a'); ?>
                    </span>
                </td>
            </tr>
            <tr>
                <th><?= $block->escapeHtml(__('Total Replies')) ?>:</th>
                <td>
                    <span class="total-replies">
                        <?= $block->escapeHtml($block->getOtherUserReplies()); ?>
                    </span>
                </td>
            </tr>
            <tr>
                <th><?= $block->escapeHtml(__('Follow this Case')) ?>:</th>
                <td>
                    <?php /* This row would show n/a if the current user is the creator or case manager */ ?>
                    <?php if ($block->getCanRenderFollowerBlock()): ?>
                        <?= sprintf('<input type="checkbox" class="follower-toggle"%s><span>%s</span>',
                            $block->getIsUserFollower() ? ' checked' : '',
                            $block->getIsUserFollower() ? __('Currently Following') : __('Not Following')
                        );
                        ?>
                        <p class="note">
                            <?= $block->escapeHtml(
                                __('You %1%2 currently receiving notifications of case replies and changes.',
                                    __('ARE'),
                                    $block->getIsUserFollower() ? '' : sprintf(' %s', __('NOT'))
                                )
                            ) ?>
                        </p>
                    <?php else: ?>
                        <?= __('n/a') ?>
                    <?php endif; ?>
                </td>
            </tr>
        </tbody>
    </table>

    <div class="fieldset-wrapper-title recent-activity">
        <span class="title"><?= $block->escapeHtml(__('Recent Activity')) ?></span>
    </div>

    <?php /* @var $reply \Dem\HelpDesk\Api\Data\ReplyInterface */ ?>
    <?php foreach ($replyItems as $reply): ?>
        <?= $block->renderReplyBlock($reply) ?>
    <?php endforeach; ?>

    <div class="a-link view-all-replies"><?= $block->escapeHtml(__('View All Replies')) ?></div>

</div>
