<?php
/**
 * HelpDesk Block - Adminhtml CaseItem View Tab Replies
 *
 * =============================================================================
 *
 * @package    Dem\HelpDesk
 * @copyright  Copyright (c) 2021 Direct Edge Media (http://directedgemedia.com)
 * @author     Toby Crain
 * @since      1.0.0
 */

/* @var $block \Dem\HelpDesk\Block\Adminhtml\CaseItem\View\Tab\Replies */
/* @var $replyItems \Dem\HelpDesk\Api\Data\ReplyInterface [] */
$replyItems = $block->getVisibleReplies();
?>

<div class="fieldset-wrapper case-information">

    <div class="fieldset-wrapper-title">
        <span class="title"><?= $block->escapeHtml(__('All Replies')) ?></span>
    </div>

    <?php /* @var $reply \Dem\HelpDesk\Api\Data\ReplyInterface */ ?>
    <?php foreach ($replyItems as $reply): ?>
        <?= $block->renderReplyBlock($reply) ?>
    <?php endforeach; ?>

</div>