<?php
/**
 * HelpDesk Block - Adminhtml CaseItem View
 *
 * =============================================================================
 *
 * @package    Dem\HelpDesk
 * @copyright  Copyright (c) 2021 Direct Edge Media (http://directedgemedia.com)
 * @author     Toby Crain
 * @since      1.0.0
 */

/* @var $block \Dem\HelpDesk\Block\Adminhtml\CaseItem\View */

?>
<?= $block->getChildHtml('case_tab_info'); ?>
<?= $block->getChildHtml('case_tab_replies');
